### ISSUE TITLE
Deprecated 

### ISSUE THREAD

**Issue by keramat-farid** [farbodbj/GuardianNews#1]
`adapterPosition` is deprecated use `bindingAdapterPosition` instead.

https://github.com/farbodbj/GuardianNews/blob/47fa4e005c8bd70f028b2b5218d904e96c77d8b6/app/src/main/java/com/bale_bootcamp/guardiannews/adapter/NewsAdapter.kt#L45C15-L45C15

**Comment by farbodbj** [comment]
RecyclerView version 1.3.1 added to build.gradle.
adapterPosition replaced with bindingAdapterPosition.

**Comment by farbodbj** [comment]
RecyclerView dependency was updated.
the replacement is done.
