### ISSUE TITLE
Best practice

### ISSUE THREAD

**Issue by keramat-farid** [farbodbj/GuardianNews#15]
There is a extension function called `asLiveData` that you can use to convert flow to live data. Its better to remove all the references to live data so you can understand collecting in fragment difficulties.

https://github.com/farbodbj/GuardianNews/blob/1ff5d7e1cf82eaffe30e24b5a9e17030fdd5e615/app/src/main/java/com/bale_bootcamp/guardiannews/ui/news/NewsFragmentViewModel.kt#L33

**Comment by farbodbj** [comment]
the fix for this issue is now at branch `issue_15` and is under testing

**Comment by farbodbj** [comment]
issue fixed in latest PR
