### ISSUE TITLE
Refresh on resume

### ISSUE THREAD

**Issue by keramat-farid** [farbodbj/GuardianNews#16]
Why are you trying to refresh your list `onResume`? 

https://github.com/farbodbj/GuardianNews/blob/1ff5d7e1cf82eaffe30e24b5a9e17030fdd5e615/app/src/main/java/com/bale_bootcamp/guardiannews/ui/news/NewsFragment.kt#L108

**Comment by farbodbj** [comment]
The ` refreshAPagingAdapter() ` was put in `onResume` to refresh the adapter only when it is empty but the conditions for emptiness were left unchecked. Needed conditions for adapter emptiness are now checked but this call may not be needed at all. It will be removed after ensuring its uselessness.

**Comment by farbodbj** [comment]
issue fixed after latest PR
