### ISSUE TITLE
Redundant async

### ISSUE THREAD

**Issue by keramat-farid** [farbodbj/GuardianNews#17]
There is no need to use async here
 https://github.com/farbodbj/GuardianNews/blob/1ff5d7e1cf82eaffe30e24b5a9e17030fdd5e615/app/src/main/java/com/bale_bootcamp/guardiannews/ui/settings/SettingsFragment.kt#L103

**Comment by farbodbj** [comment]
fix for this issue and issue #18 is under testing in branch [issues_17_18](https://github.com/farbodbj/GuardianNews/tree/issues_17_18)

**Comment by farbodbj** [comment]
issue fixed at #20

**Comment by farbodbj** [comment]
issue fixed at #20
