### ISSUE TITLE
Wrong place to setup view

### ISSUE THREAD

**Issue by keramat-farid** [farbodbj/GuardianNews#5]
You should not do anything time consuming inside `onCreateView`. The view setup must be inside `onViewCreated`
https://github.com/farbodbj/GuardianNews/blob/47fa4e005c8bd70f028b2b5218d904e96c77d8b6/app/src/main/java/com/bale_bootcamp/guardiannews/NewsFragment.kt#L44C9-L44C9

**Comment by farbodbj** [comment]
time consuming logic moved to onViewCreated
